# Generated by Django 2.2.5 on 2019-12-10 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='browse_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3, unique=True)),
                ('header', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(blank=True, max_length=999)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
