# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3, unique=True)),
                ('h1', models.CharField(max_length=999)),
            ],
        ),
    ]
