# Generated by Django 2.1.3 on 2018-11-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_lang',
            name='content',
            field=models.CharField(default=0, max_length=99999),
            preserve_default=False,
        ),
    ]
