# Generated by Django 2.1.3 on 2018-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_index_lang_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3)),
                ('logo', models.CharField(max_length=999)),
                ('text', models.CharField(max_length=99999)),
            ],
        ),
        migrations.RenameField(
            model_name='index_lang',
            old_name='content',
            new_name='h2',
        ),
    ]
