# Generated by Django 2.1.3 on 2018-12-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181230_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_lang',
            name='h2',
            field=models.TextField(default='', max_length=99999),
        ),
    ]
