# Generated by Django 2.1.3 on 2019-04-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181230_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_icon',
            name='header',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='index_icon',
            name='text',
            field=models.TextField(),
        ),
    ]
