# Generated by Django 2.1.3 on 2019-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190415_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_lang',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='index_lang',
            name='h2',
        ),
        migrations.AddField(
            model_name='index_lang',
            name='eelmine',
            field=models.CharField(default='', max_length=99999),
        ),
        migrations.AddField(
            model_name='index_lang',
            name='enne',
            field=models.CharField(default='', max_length=99999),
        ),
        migrations.AddField(
            model_name='index_lang',
            name='jargmine',
            field=models.CharField(default='', max_length=99999),
        ),
        migrations.AddField(
            model_name='index_lang',
            name='sooduspakkumised',
            field=models.CharField(default='', max_length=99999),
        ),
        migrations.AddField(
            model_name='index_lang',
            name='vaata_koiki_pakkumisi',
            field=models.CharField(default='', max_length=99999),
        ),
    ]
