# Generated by Django 2.1.3 on 2019-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190415_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_icon',
            name='link',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
