# Generated by Django 2.1.3 on 2019-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_index_icon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_icon',
            name='header',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='index_icon',
            name='logo',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='index_icon',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='index_lang',
            name='eelmine',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='index_lang',
            name='enne',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='index_lang',
            name='jargmine',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='index_lang',
            name='sooduspakkumised',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='index_lang',
            name='uuri_lahemalt',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='index_lang',
            name='vaata_koiki_pakkumisi',
            field=models.CharField(blank=True, max_length=99999),
        ),
    ]
