# Generated by Django 2.2.5 on 2019-12-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20191103_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index_icon',
        ),
    ]
