# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Gmaps_API',
            new_name='gmaps_API',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Gmaps_x',
            new_name='gmaps_x',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Gmaps_y',
            new_name='gmaps_y',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Gmaps_zoom',
            new_name='gmaps_zoom',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
