# Generated by Django 2.1.3 on 2018-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_auto_20180625_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='browser',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
