# Generated by Django 2.1.3 on 2019-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='e_store',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='navbar_lang',
            name='locations',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
