# Generated by Django 2.1.3 on 2019-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_auto_20190415_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='footer_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='navbar_lang',
            name='navigation',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
