# Generated by Django 2.1.3 on 2019-04-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0007_auto_20190415_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='open_hours',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
