# Generated by Django 2.1.3 on 2019-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0008_navbar_lang_open_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='open_hours',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
