# Generated by Django 2.1.3 on 2019-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0009_contact_open_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=999)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
    ]
