# Generated by Django 2.1.3 on 2019-11-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0010_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar_lang',
            name='e_store',
        ),
        migrations.RemoveField(
            model_name='navbar_lang',
            name='locations',
        ),
        migrations.AddField(
            model_name='navbar_lang',
            name='food_store',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.CharField(max_length=999, verbose_name='1800x400'),
        ),
    ]
