# Generated by Django 2.1.3 on 2019-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0013_navbar_lang_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.CharField(blank=True, max_length=999, verbose_name='1800x400'),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='url',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
