# Generated by Django 2.1.3 on 2019-11-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0014_auto_20191103_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar_lang',
            name='film_studio',
        ),
        migrations.RemoveField(
            model_name='navbar_lang',
            name='food_store',
        ),
    ]
