# Generated by Django 2.1.3 on 2019-11-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0015_auto_20191106_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='carrepair',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
