# Generated by Django 2.1.3 on 2019-11-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0016_navbar_lang_carrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='e_store',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='navbar_lang',
            name='locations',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
